import { useEffect, useState } from 'react'
import { Lock } from 'lucide-react'
import { PERMISSIONS } from '@/auth/permissions'
import { useAuth } from '@/auth/useAuth'
import { productsApi } from '@/features/products/api/productsApi'
import { useProductSkuSettings } from '@/features/products/hooks/useProductSkuSettings'
import { useUnitOfMeasureOptions } from '@/features/products/hooks/useUnitOfMeasureOptions'

export interface NewProductFields {
  sku: string
  unitOfMeasure: string
  packagingUnit: string
  packagingSize: string
}

export interface NewProductFieldsPanelProps {
  buyerProductId: string
  /** Fires once, right after the current values load — the parent's diff baseline. */
  onLoaded: (fields: NewProductFields) => void
  /** Fires on every edit thereafter. */
  onChange: (fields: NewProductFields) => void
}

/**
 * By the time "Confirm what you received" opens, a genuinely new marketplace purchase's product
 * row already exists — `materialize()` created it back at PLACED, from the seller's own name,
 * SKU and unit, with nobody there to ask. This is the one window left to change that: before this
 * line's first receipt writes a StockMovement, after which `Product.unitOfMeasure`'s own V19
 * immutability guard locks it for good.
 *
 * Mounted by `ReceiveOrderModal` only once the buyer has explicitly said "it's new" via
 * `DuplicateProductNudge` — never alongside it. The two used to be independent, simultaneously
 * visible toggles ("link to an existing product" and "set your own SKU" both open at once, for
 * a decision that is really one question with two answers), which read as confusing rather than
 * flexible. Sequencing them removes that: decide new-vs-existing first, and if new, this appears
 * immediately rather than behind a second link to go find.
 *
 * Saved through the existing product-update endpoint (`ProductManagementService.update`), not a
 * parallel path — its SKU-override permission check, unit validation and packaging-pair rule all
 * apply exactly as they would from the product edit screen, because this is the same edit.
 *
 * <h2>SKU auto-generation</h2>
 * When the tenant has SKU generation on, the row already carries a properly-numbered SKU (not
 * the seller's — see `IncomingStockService.matchOrCreateBuyerProduct`), and the field is locked
 * exactly the way `ProductFormPage` locks it: read-only, with an "Unlock to edit" escape hatch
 * for whoever holds `PRODUCT_SKU_OVERRIDE`. Editing SKU/unit here is otherwise the same authority
 * as editing the product directly, so this mirrors that screen rather than inventing a second
 * treatment of the same rule.
 */
export function NewProductFieldsPanel({ buyerProductId, onLoaded, onChange }: NewProductFieldsPanelProps) {
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [fields, setFields] = useState<NewProductFields | null>(null)
  const [currentUnitLabel, setCurrentUnitLabel] = useState<string | null>(null)
  const [skuUnlocked, setSkuUnlocked] = useState(false)
  const { baseOptions, packagingOptions } = useUnitOfMeasureOptions()
  const { settings: skuSettings } = useProductSkuSettings()
  const { user } = useAuth()
  const skuAutoGenerated = skuSettings?.enabled ?? false
  const canOverrideSku = user?.type === 'tenant' && user.permissions.includes(PERMISSIONS.PRODUCT_SKU_OVERRIDE)
  const skuLocked = skuAutoGenerated && !skuUnlocked

  useEffect(() => {
    let cancelled = false
    setLoading(true)
    setError(null)
    productsApi
      .get(buyerProductId)
      .then((product) => {
        if (cancelled) return
        const loaded: NewProductFields = {
          sku: product.sku,
          unitOfMeasure: product.unitOfMeasure ?? '',
          packagingUnit: product.packagingUnit ?? '',
          packagingSize: product.packagingSize != null ? String(product.packagingSize) : '',
        }
        setFields(loaded)
        setCurrentUnitLabel(product.unitOfMeasure ?? null)
        onLoaded(loaded)
      })
      .catch(() => {
        if (!cancelled) setError('Could not load this product’s current details.')
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
    // buyerProductId only — onLoaded is a fresh closure every render and must not re-trigger the fetch.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [buyerProductId])

  function update(next: Partial<NewProductFields>) {
    if (!fields) return
    const merged = { ...fields, ...next }
    setFields(merged)
    onChange(merged)
  }

  // The select can only show a value that's one of its own options — a catalog product's unit is
  // often free text copied from the seller's listing (e.g. "crate (12)") rather than one of the
  // fixed codes here, so this caption says what's actually stored even when the dropdown itself
  // can't select it. Untouched, that value is never resent, so nothing about it is at risk.
  const unitOptionCodes = new Set(baseOptions.map((option) => option.code))

  return (
    <div className="mt-2 rounded-md border border-neutral-200 bg-neutral-50 p-3">
      <p className="mb-2 text-xs font-semibold tracking-wide text-neutral-500 uppercase">New product details</p>
      {loading && <p className="text-xs text-neutral-500">Loading current details…</p>}
      {error && <p className="text-xs text-danger-600">{error}</p>}
      {fields && (
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <div>
            <div className="mb-1 flex flex-wrap items-center justify-between gap-x-2 gap-y-0.5">
              <label className="block text-xs font-medium text-neutral-700">SKU</label>
              {skuLocked && canOverrideSku && (
                <button
                  type="button"
                  onClick={() => setSkuUnlocked(true)}
                  className="shrink-0 text-xs font-medium text-primary-600 hover:underline"
                >
                  Unlock to edit
                </button>
              )}
            </div>
            {skuLocked ? (
              <div className="flex items-center gap-2 rounded-md border border-neutral-200 bg-neutral-100 px-2.5 py-1.5">
                <Lock className="h-3.5 w-3.5 shrink-0 text-neutral-400" aria-hidden="true" />
                <span className="text-sm font-medium text-neutral-700">{fields.sku}</span>
              </div>
            ) : (
              <input
                type="text"
                value={fields.sku}
                onChange={(e) => update({ sku: e.target.value })}
                className="w-full rounded-md border border-neutral-200 bg-white px-2.5 py-1.5 text-sm text-neutral-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-100 focus:outline-none"
              />
            )}
            {skuAutoGenerated && (
              <p className="mt-1 text-xs text-neutral-500">
                {skuLocked ? 'Generated automatically for this product.' : 'Overriding your own SKU scheme for this product.'}
              </p>
            )}
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-neutral-700">Stock unit</label>
            <select
              value={unitOptionCodes.has(fields.unitOfMeasure) ? fields.unitOfMeasure : ''}
              onChange={(e) => update({ unitOfMeasure: e.target.value })}
              className="w-full rounded-md border border-neutral-200 bg-white px-2.5 py-1.5 text-sm text-neutral-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-100 focus:outline-none"
            >
              <option value="">No unit</option>
              {baseOptions.map((option) => (
                <option key={option.code} value={option.code}>
                  {option.label}
                </option>
              ))}
            </select>
            {currentUnitLabel && !unitOptionCodes.has(fields.unitOfMeasure) && (
              <p className="mt-1 text-xs text-neutral-500">Currently: {currentUnitLabel}</p>
            )}
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-neutral-700">Pack</label>
            <select
              value={fields.packagingUnit}
              onChange={(e) => update({ packagingUnit: e.target.value })}
              className="w-full rounded-md border border-neutral-200 bg-white px-2.5 py-1.5 text-sm text-neutral-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-100 focus:outline-none"
            >
              <option value="">No pack</option>
              {packagingOptions.map((option) => (
                <option key={option.code} value={option.code}>
                  {option.label}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="mb-1 block text-xs font-medium text-neutral-700">Units per pack</label>
            <input
              type="number"
              min="0"
              step="any"
              inputMode="decimal"
              disabled={!fields.packagingUnit}
              value={fields.packagingSize}
              onChange={(e) => update({ packagingSize: e.target.value })}
              placeholder={fields.packagingUnit ? 'e.g. 25' : undefined}
              className="w-full rounded-md border border-neutral-200 bg-white px-2.5 py-1.5 text-sm text-neutral-900 focus:border-primary-500 focus:ring-2 focus:ring-primary-100 focus:outline-none disabled:cursor-not-allowed disabled:bg-neutral-100 disabled:text-neutral-400"
            />
          </div>
        </div>
      )}
    </div>
  )
}
