import { z } from 'zod'
import type { InitialVendorPayload, ProductFormPayload, ProductUpdatePayload } from '@/features/products/types'
import { UNIT_COPY } from '@/features/products/unitCopy'
import type { VendorMarketplaceDetailsPayload } from '@/features/vendor/types'

/**
 * Every message below is composed from `UNIT_COPY` rather than typed out, because a validation
 * message is a user-facing surface like any other and `UNIT_UX_CONTRACT.md` §7.5 — *one name per
 * concept* — does not stop at labels. These three in particular used to read "Packaged as" and
 * "Pack size", §1's banned spellings, so a form whose field said **Pack** failed with an error
 * about a field that was not on screen.
 */
const packagingSizeRequiredMessage = `Required when ${UNIT_COPY.PACK} is set`
const packagingUnitRequiredMessage = `Required when ${UNIT_COPY.UNITS_PER_PACK} is set`
/**
 * Mirrors the server's `PackagingRequiresUnitOfMeasureException`, in plainer end-user language:
 * a "Bag of 50" with no measurement unit is not a real fact — 50 what? Attached to `unitOfMeasure`
 * (the field that's missing), same pattern as the pairing rule below.
 */
const unitOfMeasureRequiredForPackagingMessage = `Required when ${UNIT_COPY.PACK} or ${UNIT_COPY.UNITS_PER_PACK} is set`
/** §1: `CompanyVendor` is a **Supplier** on every user-facing surface, errors included. */
const supplierLower = UNIT_COPY.SUPPLIER.toLowerCase()

/**
 * `Number.isFinite` rather than `!Number.isNaN`: `Number('Infinity')` is not NaN and is `>= 0`,
 * so the old test let "Infinity" through into a field that is then multiplied by a pack factor
 * and rounded (`unitSet.toBaseQuantity`). Every quantity and price on this form is a real,
 * bounded amount of something.
 */
function isNonNegativeNumber(value: string): boolean {
  return value.length > 0 && Number.isFinite(Number(value)) && Number(value) >= 0
}

/**
 * The shape `UNIT_UX_CONTRACT.md` §9.1 requires of a quantity that counts packs.
 *
 * <h2>Why these fields are no longer whole numbers</h2>
 * §9.1 is explicit: *"Decimals are accepted on both. Thirty kegs and a half-full one is a real
 * shelf, and an integer count of packs cannot say it."* Once `opening_stock` and
 * `low_stock_alert_at` count **packs** rather than stock units, an integer refinement is not a
 * safety rail — it is a rule that forbids describing an ordinary shelf. The conversion to stock
 * units still rounds, at §3.1's HALF_UP scale 0, on the way to the ledger; that rounding is the
 * server's job and the client's preview, not a constraint on what may be typed.
 *
 * <h2>The regression this closes</h2>
 * `ProductFormPage` converts a **stored** threshold back into packs when the form loads
 * (`fromBaseQuantity`, deliberately not the inverse of `toBaseQuantity` — 1,010 kg against a
 * 50 kg bag is 20.2 bags, and rounding that to 20 would invent 10 kg). Under the old
 * `isNonNegativeInteger` that product could not be saved again at all: the form filled itself in
 * with "20.2" and its own schema then refused it, so an existing product could not be edited
 * without silently rounding its alert level. Non-negotiable 3's spirit — the number on screen and
 * the number in the ledger are the same number — cannot hold if the number on screen is unsavable.
 */
function isPositiveNumber(value: string): boolean {
  return isNonNegativeNumber(value) && Number(value) > 0
}

/**
 * Still integer-only, and deliberately: the only field left using this is the stock ADJUSTMENT's
 * `newQuantity`, which is a count in **stock units** and therefore whole by construction —
 * §3.1 stores every base quantity rounded HALF_UP at scale 0, so "1,000.5 kg on hand" is not a
 * state the ledger can hold. A pack count and a base-unit count are different things and this is
 * the line between them; do not widen it without a reason from §9.1.
 */
function isNonNegativeInteger(value: string): boolean {
  return isNonNegativeNumber(value) && Number.isInteger(Number(value))
}

/** §9.1's two error messages. Composed once so the pack-counting fields all fail the same way,
 *  and so "Enter a whole number" — which is now simply untrue of them — cannot creep back in. */
const nonNegativeQuantityMessage = 'Enter a number, 0 or greater'
const positiveQuantityMessage = 'Enter a number greater than 0'

/**
 * A factory, like {@link makeStockInSchema} below, because whether `sku` is required depends on
 * a runtime tenant setting (`ProductSkuSettings.enabled`) that has nothing to do with the shape
 * of the form itself — the same reasoning the server's `CreateProductRequest` javadoc gives for
 * why `sku` isn't `@NotBlank` there either. `skuAutoGenerated` true also means the field is
 * rendered locked and pre-filled from a server preview (see `ProductFormPage`), so whatever
 * string ends up in it is never something the user typed — accepting any string here, including
 * blank while a preview is still in flight, is correct.
 */
export function makeProductFormSchema(skuAutoGenerated: boolean) {
  return z
  .object({
    name: z.string().trim().min(1, 'Name is required'),
    sku: skuAutoGenerated ? z.string() : z.string().trim().min(1, 'SKU is required'),
    description: z.string().trim(),
    // Brand does NOT go to /api/products — that endpoint has never carried it. It rides on this
    // form because it belongs on the same screen to the person filling it in, and is sent
    // separately to the seller's marketplace-details route (vendors only). Kept optional and
    // unconstrained beyond a length: a listing sells perfectly well without a brand.
    brand: z.string().trim().max(120, 'Must be 120 characters or fewer'),
    // Unit of measure (what it's fundamentally measured in — Kg, Liter, Piece), unlike brand,
    // DOES go to /api/products now — for every tenant, not just a vendor. No content rule beyond
    // "trimmed string" here even though the server only accepts one of the fixed BASE-role codes:
    // validating a dynamic, server-fetched list inside a static zod schema would either duplicate
    // that list here (the thing `useUnitOfMeasureOptions` exists to avoid) or go stale the moment
    // the backend adds a unit. Instead correctness is structural — the <select> rendering this
    // field (see ProductFormPage) is populated only with BASE-role codes the server just
    // returned, so a value this schema doesn't recognise cannot reach it from the UI. Blank is
    // fine on its own; see the superRefine below for both cross-field rules.
    unitOfMeasure: z.string().trim(),
    // How it's packaged/sold, if at all (Bag, Carton, ...) — same structural-validity-via-select
    // approach, filtered to PACKAGING-role codes. Optional on its own; required together with
    // packagingSize (superRefine below).
    packagingUnit: z.string().trim(),
    // Same numeric-string shape as unitPrice, decimals allowed ("0.5 KG" is a real count) —
    // required together with packagingUnit, never required on its own. Renamed from unitCount.
    packagingSize: z
      .string()
      .trim()
      .refine((v) => v === '' || isNonNegativeNumber(v), 'Enter a valid non-negative number'),
    // No unconditional `.min(1, ...)` here anymore: a buying company never sees this field at
    // all, and a marketplace seller leaving it blank is caught in ProductFormPage's onSubmit
    // (which knows `isVendor`; this schema does not) with the same message the server's
    // UnitPriceRequiredException uses. Still validated as a non-negative number WHEN non-empty.
    unitPrice: z
      .string()
      .trim()
      .refine((v) => v === '' || isNonNegativeNumber(v), 'Enter a valid non-negative price'),
    // No `costPrice` field here: the product's cost is a weighted-average rollup the server
    // computes from actual purchases (see MULTI_VENDOR_INVENTORY_DESIGN.md §5.3), never a value
    // typed alongside the "First vendor" block's own per-unit cost for the same purchase. That
    // block's `initialVendorCost` below is the only place a cost is entered on this form.
    // `UNIT_UX_CONTRACT.md` §9.4's `low_stock_alert_at` — labelled "Tell me when stock falls to".
    // Counts PACKS whenever the row declares one and stock units when it does not (§9.1), which
    // is why it is a plain number: see {@link isPositiveNumber} for the amendment and for the
    // edit-an-existing-product regression the old integer rule caused.
    lowStockThreshold: z
      .string()
      .trim()
      .refine((v) => v === '' || isNonNegativeNumber(v), nonNegativeQuantityMessage),
    // ---- "First vendor" (§7.1) — create-only, optional as a whole. A plain optional id with no
    // shape rule, same reasoning the old companyVendorId field used: the select only ever offers
    // ids the server just sent back, and the server re-resolves whatever arrives against the
    // caller's own directory anyway. Empty means "no vendor yet", the normal state for a product
    // catalogued ahead of its first delivery.
    initialVendorId: z.string().trim(),
    // Required together with initialVendorId (superRefine below), never on its own. Decimals
    // allowed, same shape as unitPrice.
    initialVendorCost: z
      .string()
      .trim()
      .refine((v) => v === '' || isNonNegativeNumber(v), 'Enter a valid non-negative cost'),
    // `opening_stock` (§9.4) — the opening stock-in quantity for this supplier. Counted in PACKS
    // whenever the product declares one (§9.1), so decimals are accepted: "30.5 kegs" is a real
    // opening shelf. Still > 0 — a stock movement of zero isn't a movement.
    initialVendorQuantity: z
      .string()
      .trim()
      .refine((v) => v === '' || isPositiveNumber(v), positiveQuantityMessage),
  })
  // Mirrors the server's two packaging rules. Caught here, before the request, with each error
  // attached to whichever field is missing — the server's flat `{message}` bodies wouldn't know
  // which field to point at, and a general form error for a two- or three-field mistake makes
  // someone hunt for it.
  .superRefine((values, ctx) => {
    const hasUnit = values.unitOfMeasure.length > 0
    const hasPackagingUnit = values.packagingUnit.length > 0
    const hasPackagingSize = values.packagingSize.length > 0

    // Rule 1 — mirrors PackagingUnitAndSizeRequiredTogetherException: packagingUnit and
    // packagingSize must arrive together or not at all.
    if (hasPackagingUnit && !hasPackagingSize) {
      ctx.addIssue({ code: 'custom', path: ['packagingSize'], message: packagingSizeRequiredMessage })
    }
    if (hasPackagingSize && !hasPackagingUnit) {
      ctx.addIssue({ code: 'custom', path: ['packagingUnit'], message: packagingUnitRequiredMessage })
    }

    // Rule 2 — mirrors PackagingRequiresUnitOfMeasureException: if either packaging field is
    // set, unitOfMeasure must also be set. One-directional — unitOfMeasure alone, no packaging,
    // stays valid.
    if ((hasPackagingUnit || hasPackagingSize) && !hasUnit) {
      ctx.addIssue({ code: 'custom', path: ['unitOfMeasure'], message: unitOfMeasureRequiredForPackagingMessage })
    }

    // Rule 3 — the "First vendor" block (§7.1) is optional as a whole, but its three fields are
    // all-or-nothing together: picking a vendor with no cost/quantity would create a
    // `ProductVendor` row with no opening stock to show for it, and entering a cost or quantity
    // with no vendor chosen has nowhere on the server to attach to.
    const hasInitialVendor = values.initialVendorId.length > 0
    const hasInitialCost = values.initialVendorCost.length > 0
    const hasInitialQuantity = values.initialVendorQuantity.length > 0
    if (hasInitialVendor && !hasInitialCost) {
      ctx.addIssue({ code: 'custom', path: ['initialVendorCost'], message: `Required when a ${supplierLower} is selected` })
    }
    if (hasInitialVendor && !hasInitialQuantity) {
      ctx.addIssue({
        code: 'custom',
        path: ['initialVendorQuantity'],
        message: `Required when a ${supplierLower} is selected`,
      })
    }
    if ((hasInitialCost || hasInitialQuantity) && !hasInitialVendor) {
      ctx.addIssue({
        code: 'custom',
        path: ['initialVendorId'],
        message: `Select a ${supplierLower} to record cost or quantity`,
      })
    }
  })
}

export type ProductFormValues = z.infer<ReturnType<typeof makeProductFormSchema>>

/**
 * The /api/products half of the form. Brand is deliberately absent: that endpoint does not
 * accept it, and sending it would be silently dropped — see {@link toVendorMarketplaceDetailsPayload}
 * for where it actually goes. Unit of measure and the packaging pair, unlike brand, DO belong
 * here now for every tenant.
 *
 * <p>`unitPrice` is sent only when the caller typed one — omitted, not `0`, when blank. The
 * server enforces "required for a seller" itself; a buying company's blank value is correctly
 * silently discarded there.
 *
 * <h2>`lowStockThreshold` here is NOT ready to send — the caller must convert it</h2>
 * `UNIT_UX_CONTRACT.md` §9.1: the form field counts **packs** whenever the product declares one.
 * The wire field is, and stays, stock units. This function is a pure field-shaping mapper with no
 * access to the product's unit set, so it can only pass the typed number through; `ProductFormPage`
 * overwrites it with `toStockUnits(values.lowStockThreshold)` (§3.1's HALF_UP scale 0) immediately
 * after spreading this result, and any future caller must do the same. The same applies to
 * `initialVendor.quantity` in {@link toInitialVendorPayload}. Leaving the multiplication to the one
 * component that holds the unit set beats threading the set through a schema module — but it is a
 * seam, so it is written down here rather than left to be rediscovered.
 */
export function toProductPayload(values: ProductFormValues): ProductFormPayload {
  return {
    name: values.name,
    sku: values.sku,
    description: values.description || undefined,
    unitPrice: values.unitPrice ? Number(values.unitPrice) : undefined,
    unitOfMeasure: values.unitOfMeasure || undefined,
    packagingUnit: values.packagingUnit || undefined,
    packagingSize: values.packagingSize ? Number(values.packagingSize) : undefined,
    lowStockThreshold: values.lowStockThreshold ? Number(values.lowStockThreshold) : undefined,
  }
}

/**
 * The "First vendor" block (§7.1) as the `initialVendor` the create request wants — the first
 * `ProductVendor` row and its opening stock-in, folded into product creation itself. `undefined`
 * when the (optional) block was left blank, which is the normal case for a product catalogued
 * with no vendor or stock yet; the schema's superRefine guarantees cost/quantity are present
 * whenever a vendor id is, so `Number(...)` below is never fed an empty string.
 *
 * <p>Create-only by convention, not by type: `ProductFormPage` never renders this section in
 * edit mode, so `values.initialVendorId` is always `''` there and this always returns
 * `undefined` on an update.
 *
 * <p>`quantity` is the typed number in the form's own unit — packs under §9.1 — and the caller
 * converts it to stock units before sending, exactly as it does for `lowStockThreshold`. See
 * {@link toProductPayload}.
 */
export function toInitialVendorPayload(values: ProductFormValues): InitialVendorPayload | undefined {
  if (!values.initialVendorId) return undefined
  return {
    companyVendorId: values.initialVendorId,
    cost: Number(values.initialVendorCost),
    quantity: Number(values.initialVendorQuantity),
  }
}

/**
 * The update half of the payload. Now a thin alias over `toProductPayload` — the old reason for
 * this being a separate function (expressing "clear the supplier" with `clearCompanyVendor`,
 * since an absent `companyVendorId` meant "leave it alone") no longer applies: there is no flat
 * per-product supplier field left to clear. Kept as its own export because `ProductFormPage`
 * calls it by name and a product no longer has just one vendor to reason about here at all — see
 * the Vendors tab for how an existing product's `ProductVendor` rows are actually managed.
 */
export function toProductUpdatePayload(values: ProductFormValues): ProductUpdatePayload {
  return toProductPayload(values)
}

/**
 * The other half, for the seller's own marketplace-details route — brand only now. Unit of
 * measure used to travel here too; it moved to {@link toProductPayload}, and this route's
 * payload type no longer has a component for it.
 *
 * <p>Empty string is sent as `''`, not omitted, and the difference matters: an omitted field
 * means "leave as is" server-side, so a vendor clearing a brand they typed by mistake would
 * find it still there. The server normalises blank to null (`blankToNull`), which is the
 * clear. Omitting it would make the field one-way.
 *
 * <p>No `slug` — a vendor may not author one, and the payload type has no such component.
 */
export function toVendorMarketplaceDetailsPayload(
  values: ProductFormValues,
): VendorMarketplaceDetailsPayload {
  return {
    brand: values.brand,
  }
}

export function productFormDefaults(): ProductFormValues {
  return {
    name: '',
    sku: '',
    description: '',
    brand: '',
    unitOfMeasure: '',
    packagingUnit: '',
    packagingSize: '',
    unitPrice: '',
    lowStockThreshold: '',
    initialVendorId: '',
    initialVendorCost: '',
    initialVendorQuantity: '',
  }
}

export const requestUnitOfMeasureSchema = z.object({
  requestedUnit: z
    .string()
    .trim()
    .min(1, 'Tell us what unit you need')
    .max(200, 'Must be 200 characters or fewer'),
  note: z.string().trim().max(1000, 'Must be 1000 characters or fewer'),
})

export type RequestUnitOfMeasureFormValues = z.infer<typeof requestUnitOfMeasureSchema>

const noteField = z.string().trim().max(1000, 'Must be 1000 characters or fewer')

/**
 * The quantity typed into either stock modal, in whatever unit the "Counted in" control says.
 *
 * Not a whole number, for the same reason §9.1 gives for the catalog's two quantities: the number
 * being typed is usually a count of PACKS, and half a bag is an ordinary delivery. It is also what
 * the rest of the contract already assumed — §3.1 computes `round(quantity × factorToStockUnit)`
 * HALF_UP at scale 0 (a rounding that has nothing to do if the input is whole and the factor is an
 * integer), and §3.3 stores what the human typed in `entered_quantity numeric(14,3)`, three
 * decimals the old integer rule made unreachable.
 *
 * The ceiling is deliberately absent — see {@link stockOutSchema} — and so is any unit rule: the
 * unit comes from the product's derived set, not from free text (see {@link makeStockInSchema}).
 */
const quantityField = z
  .string()
  .trim()
  .min(1, 'Quantity is required')
  .refine((v) => v.length === 0 || isPositiveNumber(v), positiveQuantityMessage)

/**
 * Stock-in's form schema. `vendorRequired` is threaded in rather than baked in statically
 * because whether a supplier must be picked depends on data fetched at runtime (does this product
 * already have a `ProductVendor` row, is the company's supplier directory even non-empty) — see
 * `StockInModal`'s supplier-field logic, which mirrors §7.3 of the multi-vendor inventory design:
 * the user only ever picks a supplier when it's actually ambiguous or new.
 *
 * <h2>The three fields behind "This delivery came in a different pack"</h2>
 * `packagingUnit`/`packagingSize` are THIS delivery's pack — `UNIT_UX_CONTRACT.md` §3.1's
 * per-request override, which extends the product's unit set for one request and is snapshotted
 * onto the resulting `StockMovement`. `saveAsSupplierDefault` is §3.4's explicit opt-in for also
 * writing that pack back to `ProductVendor` as the supplier's standing default. It is a boolean
 * rather than a string because it is a checkbox with no invalid state, and it lives in the schema
 * rather than in component state so that the pack and the decision about the pack are read back
 * from one place — plan §3's P0-5 was precisely those two facts drifting apart, the UI promising
 * a default was untouched while the request rewrote it.
 *
 * The unit a quantity is COUNTED IN is deliberately not here: it is chosen from the product's
 * derived unit set (§2), which is fetched data rather than free text, so a static schema has
 * nothing to validate that the closed set does not already guarantee. `StockInModal` holds it as
 * plain state and resolves it through `unitSet.findUnitOption`, which is the only check that
 * means anything — §7.1's *no quantity field offers a unit with no conversion factor* holds
 * structurally there, not by validation here.
 */
export function makeStockInSchema(vendorRequired: boolean) {
  return z
    .object({
      quantity: quantityField,
      unitPrice: z.string().trim().refine((v) => v === '' || isNonNegativeNumber(v), 'Enter a valid non-negative price'),
      companyVendorId: z.string().trim(),
      packagingUnit: z.string().trim(),
      packagingSize: z
        .string()
        .trim()
        .refine((v) => v === '' || isNonNegativeNumber(v), 'Enter a valid non-negative number'),
      saveAsSupplierDefault: z.boolean(),
      note: noteField,
    })
    .superRefine((values, ctx) => {
      if (vendorRequired && values.companyVendorId.trim().length === 0) {
        ctx.addIssue({ code: 'custom', path: ['companyVendorId'], message: `Choose a ${supplierLower}` })
      }
      // Both or neither — mirrors the server's `PackagingUnitAndSizeRequiredTogetherException`,
      // and more immediately: a pack with no size is not a conversion, so `unitSet.buildPackOption`
      // would return null and the toggle would silently gain no option at all.
      const hasPackagingUnit = values.packagingUnit.length > 0
      const hasPackagingSize = values.packagingSize.length > 0
      if (hasPackagingUnit && !hasPackagingSize) {
        ctx.addIssue({ code: 'custom', path: ['packagingSize'], message: packagingSizeRequiredMessage })
      }
      if (hasPackagingSize && !hasPackagingUnit) {
        ctx.addIssue({ code: 'custom', path: ['packagingUnit'], message: packagingUnitRequiredMessage })
      }
    })
}

export type StockInFormValues = z.infer<ReturnType<typeof makeStockInSchema>>

/**
 * Stock-out's form schema — deliberately just quantity and note. No supplier, no unit-validation
 * beyond "a positive whole number": per §6/§7.5 of the design, lot allocation is either left to
 * server-side FIFO (simple path) or built against the open lots from
 * `GET /api/products/{id}/lots` in the "Choose which deliveries this comes from" disclosure,
 * neither of which is a free-text field this schema needs to police. The available-
 * quantity ceiling is intentionally NOT enforced here (unlike the old `makeStockQuantitySchema`)
 * because once the unit toggle lets someone enter "3 bags", checking against a base-unit
 * `currentQuantity` needs a live unit conversion this static schema has no access to — the
 * server's 409 (with the actual available/requested numbers) is the authoritative check instead.
 */
export const stockOutSchema = z.object({
  quantity: quantityField,
  note: noteField,
})

export type StockOutFormValues = z.infer<typeof stockOutSchema>

/**
 * Stock adjustment — a correction that SETS the on-hand figure rather than moving it.
 *
 * The one quantity on this feature that is still a whole number, and it stays one on purpose:
 * `StockAdjustmentModal` has no "Counted in" control, so `newQuantity` is read directly as **stock
 * units**, and §3.1 keeps every base quantity at HALF_UP scale 0. §9.1's decimals apply to counts
 * of packs; this is not one. If this modal ever grows a unit toggle, this refinement moves with it.
 */
export const stockAdjustmentSchema = z.object({
  newQuantity: z
    .string()
    .trim()
    .min(1, 'New quantity is required')
    .refine((v) => v.length === 0 || isNonNegativeInteger(v), 'Enter a whole number, 0 or greater'),
  note: z.string().trim().min(1, 'A reason is required').max(1000, 'Must be 1000 characters or fewer'),
})

export type StockAdjustmentFormValues = z.infer<typeof stockAdjustmentSchema>
