export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
